/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package stratego;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class MiPerfil extends javax.swing.JFrame {

    ArrayList<Usuario> Usuarios;
       ArrayList<Logs> Todoslos_Logs;
    int indexUser;
    int Puntos, JugadasH, JugadasV;

    /**
     * Creates new form MiPerfil
     */
    public MiPerfil(int UserIndex, ArrayList UsuariosObtenidos, ArrayList<Logs> Todoslos_Logs_A) {
        indexUser = UserIndex;
        Usuarios = UsuariosObtenidos;

            Todoslos_Logs = new ArrayList<Logs>();
        if(Todoslos_Logs_A != null){
            Todoslos_Logs= Todoslos_Logs_A;
        }
        
        
        
        initComponents();

        
        
         String Texto = 
                "<html><br><br>Nombre: "+ Usuarios.get(indexUser).getUser()+"<br><br>"
                + "\nPuntos: " +  Usuarios.get(indexUser).getPuntos() +"<br><br>"
              
                + "\nJugadas Heroes"+   Usuarios.get(indexUser).getPartidasHeroe()+"<br><br>"
                + "\nJugadas Villano: "+Usuarios.get(indexUser).getPartidasVillano()+ "</html>";
        
        jLabel1.setText(Texto);
        
        
        /*
        "Nombre: " + Usuarios.get(indexUser).getUser() + "\n"
                + "Puntos: " + Usuarios.get(indexUser).getPuntos() + "\n"
                + "PH: " +  Usuarios.get(indexUser).getPartidasHeroe() + "\n"
                + "PV: " + Usuarios.get(indexUser).getPartidasVillano()
        */
    this.setSize(472, 537);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Log de mis ultimos Juegos");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 229, 47));

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre: ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 330, 180));

        jButton4.setText("Volver");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 460, 160, 30));

        jButton5.setText("Cambiar mi Password");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 230, 50));

        jButton6.setText("Eliminar mi Cuenta");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 230, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/MiPerfil.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked

        Log_de_UltimosJuegos ObjLOGS = new Log_de_UltimosJuegos(this.indexUser, this.Usuarios, this.Todoslos_Logs);
        ObjLOGS.setVisible(true);
     this.setVisible(false);
        
        
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
   
        
        MenuPrincipal ObjMenuPrincipal = new MenuPrincipal(indexUser, Usuarios, true, this.Todoslos_Logs);
        
        
        ObjMenuPrincipal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
   try{
        String Contra = JOptionPane.showInputDialog("Ingrese su Contraseña Actual: ");
     
     if(Usuarios.get(indexUser).getContra().equals(Contra)){
         String ContraNueva= "";
         do{
            
               ContraNueva = JOptionPane.showInputDialog("Ingrese Nueva Contraseña (debe ser de 5 caracteres): ");
         }while(ContraNueva.length() != 5);
         
     Usuarios.get(indexUser).setContra(ContraNueva);
         
     
     
     
         JOptionPane.showMessageDialog(null, "La contraseña se cambio correctamente");
     }else{
             JOptionPane.showMessageDialog(null, "La contraseña no es correcta");
     }   
               
         }catch (Exception e){
               JOptionPane.showMessageDialog(null, "Operacion Cancelada");
         }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        try{
         String Contra = JOptionPane.showInputDialog("Ingrese su Contraseña: ");
     
     if(Usuarios.get(indexUser).getContra().equals(Contra) &&Usuarios.get(indexUser).isActivo() ){
          Usuarios.get(indexUser).setActivo(false);
          
          
                        JOptionPane.showMessageDialog(null, "Usuario eliminado exitosamente");
                MenuInicial ObjMenuI = new MenuInicial(this.Usuarios, this.Todoslos_Logs);
                ObjMenuI.setVisible(true);
                this.setVisible(false);
     }else{
             JOptionPane.showMessageDialog(null, "La contraseña no es correcta");
     }   
            }catch (Exception e){
               JOptionPane.showMessageDialog(null, "Operacion Cancelada");
         }   
    }//GEN-LAST:event_jButton6MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiPerfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiPerfil(-1, null,null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
